from __future__ import annotations

class V8:
    @staticmethod
    def init() -> None: ...
    @staticmethod
    def shutdown() -> None: ...
    @staticmethod
    def compile(src: str) -> bytearray: ...
