from __future__ import annotations

class V8System:
    @staticmethod
    def compile_and_invoke(src: str) -> str: ...
    @staticmethod
    def compile_to_snapshot(src: str) -> bytes: ...
    @staticmethod
    def invoke_snapshot(snapshot: bytes) -> str: ...
