from __future__ import annotations

class V8System:
    @staticmethod
    def compile_and_invoke_source(source: str) -> str: ...
    @staticmethod
    def compile_source_to_snapshot(source: str) -> bytes: ...
    @staticmethod
    def invoke_function(function_id: str, source: str, snapshot: bytes) -> str: ...
